In [1]:
N,X,Y = (map(int, input().split()))

A = [0 for _ in range(N)]

A[0] = X
A[1] = Y
for i in range(2,N,1):
    A[i] = (A[i-1] + A[i-2]) % 100
print(A[-1])



ValueError: not enough values to unpack (expected 3, got 0)

In [ ]:
N = int(input())
A = list(map(int,input().split()))

dp = [float('inf')] * N

dp[0] = 0
dp[1] = A[1]
for i in range(2,N):
    dp[i] = min(dp[i-1] + A[i], dp[i-2] + 2 * A[i])
print(dp[-1])

In [ ]:
N = int(input())

A = [0] * N
A[0] = 1
A[1] = 1

for i in range(2,N+1):
    A[i] = A[i-1] + A[i-2]
print(A[N])


3


In [ ]:
A[0] = 1
A[1] = 1
A[2] = A[1] +1  = 2
A[3] = A[2] + A[1] = 4
a[4] = 7
a[5]


1 3
2 2
3 1

In [ ]:
dp[4] = dp[3] + dp[2] + dp[1]

In [ ]:
N = int(input())

dp = [0] * (N+1)

dp[0] = 1
dp[1] = 1

if N > 1: dp[2] = 2

for i in range(3,N+1):
    dp[i] = dp[i-1] + dp[i-2] +  dp[i-3]
    
print(dp[N])

1


In [ ]:
N, M  = map(int, input().split())
A = list(map(int, input().split()))

dp = [0] * (N)
for i in range(1,N):
    for j in range(1,M+1):
        if j > i:
            break
        dp[i] = min(dp[i], dp[i-j] + j*A[i])
print(dp[-1])

0


In [ ]:
N, M  = map(int, input().split())
D = list(map(int, input().split()))

dp = [0] * (N+1)
dp[0] = 1
for i in range(N+1):
    for j in range(M): 
        if i < D[j]:
            continue
        dp[i] += dp[i-D[j]]
if dp[-1] > 0:
    print('Yes')
else:
    print('No')

No


In [ ]:
import numpy as np


array(1)

In [ ]:
import numpy as np

N = int(input())
A = np.array([list(map(int, input().split()))])
A = np.concatenate([A,np.zeros([N-1,N])])

for i in range(1,N):
    for j in range(N):
        if j > 0 and j < N-1:
            A[i][j] = (A[i-1][j-1] + A[i-1][j] + A[i-1][j+1]) % 100
        elif j > 0:
            A[i][j] = (A[i-1][j] + A[i-1][j-1]) % 100
        elif j < N-1:
            A[i][j] = (A[i-1][j] + A[i-1][j+1]) % 100
print(int(A[-1][-1]))


25


In [ ]:
print(A)
print(np.zeros([3,4]))

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
N = 3
for i in range(N):
    for j in range(N):
        print(i,j)

print('-' * 30)

for i in range(N):
    for j in range(i,N):
        print(i,j)





0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2
------------------------------
0 0
0 1
0 2
1 1
1 2
2 2


In [ ]:
import numpy as np
from math import sin, cos, radians
a,b,d = map(int, input().split())

A = np.array([a,b])
t = radians(-d)
D = np.array([[cos(t), -sin(t)],[sin(t), cos(t)]])
ans = np.dot(A,D)
print(f'{ans[0]},{ans[1]}')


-259.423617114473,-473.5033124311205


In [ ]:
D

array([[ 0.1391731 ,  0.99026807],
       [-0.99026807,  0.1391731 ]])

In [ ]:
d = 360
t = radians(d)
np.array([[cos(t), -sin(t)],[sin(t), cos(t)]])

array([[ 1.0000000e+00,  2.4492936e-16],
       [-2.4492936e-16,  1.0000000e+00]])

In [ ]:
#!/usr/bin/env python3

def main():
    import numpy as np
    from math import sin, cos, radians
    a,b,d = map(int, input().split())

    A = np.array([a,b])
    t = radians(-d)
    D = np.array([[cos(t), -sin(t)],[sin(t), cos(t)]])
    ans = np.dot(A,D)
    print(f'{ans[0]} {ans[1]}')

main()


ValueError: not enough values to unpack (expected 3, got 0)

In [8]:
#!/usr/bin/env python3

def main():
    S = input()
    T = input()
    
    lst = []
    j = 0
    flag = False

    for i in range(len(S)-1):
        if S[i] == S[i+1]:
            lst.append(i)


    # print(lst)
    

    if T == S:
        flag = True
    
    while len(lst) > 0 and j+len(S) <= len(T):
        for i in lst:
            S_ = S[:i] + j * S[i] + S[i:]
            # print(S_)
            if T == S_:
                flag = True
                break

        j += 1

    
    if flag:
        print('Yes')
    else:
        print('No')

main()


No


In [ ]:
#!/usr/bin/env python3

def main():
    S = input()
    T = input()
    
    lst = []
    j = 0
    flag = False

    for i in range(len(S)-1):
        if S[i] == S[i+1]:
            lst.append(i)

    dp = [0] * N
    
    n = [0] * len(lst) 
    
    for l in lst:
        S[:]

    for i in range():
        
    
    if flag:
        print('Yes')
    else:
        print('No')

main()


In [ ]:

func(S,i,)

In [ ]:
'affggt'
'afffffgggggggttttppi'


num[j] * S[]

for lst []

S[:i]+ num[]S[i] + S[i:]





In [9]:
S = "afftggm"
list(S)

['a', 'f', 'f', 't', 'g', 'g', 'm']

In [ ]:

lst = [[0,1],[1,2],[4,2],[5,1]]

S[0:lst[0][0]] + lst[0][1] * S[1] + S[lst[0][0]:lst[1]] + num[1] * S[4] + S[4:]
S[]

In [ ]:
N = len(T)
lst = [3,6]
S[lst[i]]

In [10]:
a, b = map(int, input().split())

c = a * b

if c % 2 == 0:
    print('Even')
else:
    print('Odd')

Odd


In [12]:
s = input()

cnt = 0
for c in s:
    if c == '1':
        cnt += 1
print(cnt)
    

2


In [17]:
N = int(input())
A = list(map(int, input().split()))

A.sort(reverse=True)

al = 0
bo = 0

for i in range(N):
    if i % 2 == 0:
        al += A[i]
    else:
        bo += A[i]

print(al - bo)



5


In [19]:
#!/usr/bin/env python3

def main():
    N,K = map(int, input().split())
    L = list(map(int, input().split()))

    L.sort(reverse=True)
    print(sum(L[:K]))

main()


1


In [ ]:
N,x = map(int, input().split())
A = list(map(int, input().split()))

A.sort()
total = 0

for i in range(N):
    if x < A[i]:
        break
    total += 1
    x -= A[i]

print(total)


